### PR TITLE
Homepage_v1

### PR DESCRIPTION
**Pull request by Harshal543**
Few Bugs are to be removed

### CODE REVIEW

**Comment by darth-dodo** [comment]
What bugs are these? Please list them out. Who will be working on them? Please add others as mentions to this comment chain @Harshal543 @djpandit007 using '@<username>'.

**Comment by darth-dodo** [comment]
@Harshal543 , @djpandit007 Any reasons why the CSS isn't a single file and split into multiple files? This makes things extremely hard for debugging. If the reason is distributed development, please consolidate it into a single file and create a new request. Define a folder structure such as given below. Following that change the imports in the html.

dodo@darth-dodo~/Desktop/homepage
$ tree
.
├── css
│   └── homepage.css
├── index.html
├── js
│   └── homepage.js
└── media
    ├── gifs
    │   └── whynofolderstruture.gif
    └── images
        ├── fb-icon.jpeg
        ├── logo.jpg
        └── twitter-icon.jpg

5 directories, 7 files

**Comment by darth-dodo** [comment]
@Harshal543, @djpandit007: The pull request should be a feature branch against the master. Not master against master

**Comment by puneet-lumos** [comment]
@darth-dodo Currently known bugs (After merging css files and js files) -
- First section animation background not working
- Partially Responsive
- Blank gaps between sections
- Last section footer size 
- Unable to load font on last section

Yet to be implemented - 
- Section wise scrolling 
- Deciding color scheme

**Pull request closed without merging**
